name: test

on:
  workflow_dispatch:
      inputs:
        test:
          type: string
          required: true
      inputs:
        test:
          type: string
          required: true

run-name: test-${{inputs.test}}

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - name: clone
      run: cd .. && git clone --quiet --filter=tree:0 --single-branch https://github.com/humbletim/cpp-pdk
    - name: fetch sdks
      run: make fetch-linux-sdks
    - name: all
      run: make all
    - name: test
      run: make test
    - name: report
      run: make report 2>&1 | tee $GITHUB_STEP_SUMMARY
    - name: ~Setup tmate session
      if: failure()
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true

