name: test

on:
  workflow_dispatch:
      inputs:
        test:
          type: string
          required: true

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - name: Output Inputs
      shell: bash
      run: |
        make fetch-linux-sdks
        make test
